### ISSUE TITLE
国际服当前版本启用本悬浮窗后OP控制台会报错

### ISSUE THREAD

**Issue by subjadeites** [Jiacheng-z/FFXIV-Monitor-Tools#40]
报错文本如下：
Error: 订阅的事件 "onPartyWipe" 未注册!

目前没看出有什么严重后果，暂时还在能用的状态。但是开ACT可能会导致任务栏假死，暂时没有做详细排查是ACT本体的原因还是解析插件的原因还是OP的原因。

**Comment by lsl1225** [comment]
没有影响，原版act已经把onPartyWipe事件移除了，act导致的任务栏假死应该是别的原因
